import {
  adminLogin,
  adminRegister,
  authRouteInfo,
  createSettingUser,
  createSettingVendor,
  currentUser,
  deleteSettingUser,
  deleteSettingVendor,
  listSettingUsers,
  listSettingVendors,
  staffLogin,
  unifiedLogin,
  userRegister,
  updateCurrentUser,
  updateSettingUserStatus,
  updateSettingVendorStatus,
  vendorLogin,
  vendorRegister,
} from '../controllers/authController.js'

export const authRoutes = [
  { method: 'GET', path: '/api/auth/admin/register', handler: (request) => authRouteInfo(request, { endpoint: '/api/auth/admin/register' }) },
  { method: 'GET', path: '/api/auth/admin/login', handler: (request) => authRouteInfo(request, { endpoint: '/api/auth/admin/login' }) },
  { method: 'GET', path: '/api/auth/staff/login', handler: (request) => authRouteInfo(request, { endpoint: '/api/auth/staff/login' }) },
  { method: 'GET', path: '/api/auth/vendor/register', handler: (request) => authRouteInfo(request, { endpoint: '/api/auth/vendor/register' }) },
  { method: 'GET', path: '/api/auth/user/register', handler: (request) => authRouteInfo(request, { endpoint: '/api/auth/user/register' }) },
  { method: 'GET', path: '/api/auth/vendor/login', handler: (request) => authRouteInfo(request, { endpoint: '/api/auth/vendor/login' }) },
  { method: 'GET', path: '/api/auth/login', handler: (request) => authRouteInfo(request, { endpoint: '/api/auth/login' }) },
  { method: 'GET', path: '/api/auth/me', handler: currentUser },
  { method: 'GET', path: '/api/settings/users', handler: listSettingUsers },
  { method: 'GET', path: '/api/settings/vendors', handler: listSettingVendors },
  { method: 'POST', path: '/api/auth/admin/register', handler: adminRegister },
  { method: 'POST', path: '/api/auth/user/register', handler: userRegister },
  { method: 'POST', path: '/api/auth/admin/login', handler: adminLogin },
  { method: 'POST', path: '/api/auth/staff/login', handler: staffLogin },
  { method: 'POST', path: '/api/auth/login', handler: unifiedLogin },
  { method: 'POST', path: '/api/auth/me', handler: updateCurrentUser },
  { method: 'POST', path: '/api/settings/users', handler: createSettingUser },
  { method: 'POST', path: /^\/api\/settings\/users\/([^/]+)\/status$/, params: ['id'], handler: updateSettingUserStatus },
  { method: 'DELETE', path: /^\/api\/settings\/users\/([^/]+)$/, params: ['id'], handler: deleteSettingUser },
  { method: 'POST', path: '/api/settings/vendors', handler: createSettingVendor },
  { method: 'POST', path: /^\/api\/settings\/vendors\/([^/]+)\/status$/, params: ['id'], handler: updateSettingVendorStatus },
  { method: 'DELETE', path: /^\/api\/settings\/vendors\/([^/]+)$/, params: ['id'], handler: deleteSettingVendor },
  { method: 'POST', path: '/api/auth/vendor/register', handler: vendorRegister },
  { method: 'POST', path: '/api/auth/vendor/login', handler: vendorLogin },
]
